# Kanagawa Wave Theme Colors
[colors.primary]
background = "#1F1F28" # winterBlue
foreground = "#DCD7BA" # fujiWhite

[colors.cursor]
cursor = "#7FB4CA" # waveAqua2
text = "#1F1F28"   # winterBlue (contrast for cursor)

[colors.selection]
background = "#223249" # waveBlue2
text = "#DCD7BA"       # fujiWhite

[colors.normal]
black = "#1F1F28"   # winterBlue
red = "#E46876"     # waveRed
green = "#98BB6C"   # waveGreen
yellow = "#DCD478"  # waveYellow
blue = "#7FB4CA"    # waveAqua2
magenta = "#957FB8" # wavePurple
cyan = "#6A9589"    # waveAqua1
white = "#DCD7BA"   # fujiWhite

[colors.bright]
black = "#2D4F67"   # waveBlue1 (brighter black)
red = "#E46876"     # waveRed
green = "#98BB6C"   # waveGreen
yellow = "#DCD478"  # waveYellow
blue = "#7FB4CA"    # waveAqua2
magenta = "#957FB8" # wavePurple
cyan = "#6A9589"    # waveAqua1
white = "#C8C093"   # oldWhite (brighter white)

[[colors.indexed_colors]]
index = 16
color = "#FFA066" # waveOrange

[[colors.indexed_colors]]
index = 17
color = "#2D4F67" # waveBlue1 (using as an additional distinct color)

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
option_as_alt = "Both"
opacity = 1
padding.x = 10
padding.y = 10

[env]
TERM = "xterm-256color"
