"$schema" = "https://starship.rs/config-schema.json"

format = """\
($directory)\
$os\
$git_branch\
$fill\
$nodejs\
$rust\
$golang\
$php\
$bun\
$java\
$c\
$conda\
$zig\
$cmd_duration\
$time\
\n$character\
"""

# Disable the blank line at the beginning of the prompt
add_newline = true

# Command timeout
command_timeout = 3600000

# carbonfox color settings
palette = "carbonfox"

[fill]
symbol = ' '

[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
purple = "#be95ff"
yellow = "#08bdba"
os_bg = "#7b7c7e"
os_fg = "#0c0c0c"
dir_bg = "#25be6a"
dir_fg = "#161616"
git_bg = "#08bdba"
git_fg = "#252525"
lang_bg = "#78a9ff"
lang_fg = "#353535"
arrow = "#25be6a"      # carbonfox green
os = "#7b7c7e"         # carbonfox os_bg
directory = "#be95ff"
git = "#08bdba"        # carbonfox yellow
duration = "#be95ff"   # carbonfox purple
text_color = "#25be6a" # carbonfox green
text_light = "#161616" # carbonfox dir_fg

# Pink FC icon for the prompt
[character]
success_symbol = "[ ](fg:#78a9ff)" # FC in carbonfox green
error_symbol = "[ ](fg:#ee5396)"      # FC in carbonfox red if there is an error

# User settings
[username]
style_user = 'bold fg:os'
style_root = 'bold fg:red'
format = '[  $user](fg:$style) ' # FC before the username
disabled = false
show_always = true

# Directory settings
[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 2
style = "fg:directory"
read_only_style = "fg:directory"
before_repo_root_style = "fg:directory"
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[cmd_duration]
format = " took [ $duration]($style) "
style = "bold fg:purple"
min_time = 500

[git_branch]
format = "󰧂 [$symbol$branch]($style) "
style = "bold fg:git"
symbol = " "

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "fg:text_color"

[docker_context]
disabled = true
symbol = " "

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))](fg:#78a9ff)($style)'
symbol = ""
version_format = "${raw}"

[java]
format = '[[ $symbol ($version) ](fg:#ee5396)]($style)'
version_format = "${raw}"
symbol = " "
disabled = false

[c]
format = '[[ $symbol ($version) ](fg:#08bdba)]($style)'
symbol = " "
version_format = "${raw}"
disabled = false

[zig]
format = '[[ $symbol ($version) ](fg:#be95ff)]($style)'
version_format = "${raw}"
disabled = false

[bun]
version_format = "${raw}"
format = '[[ $symbol ($version) ](fg:#25be6a)]($style)'
disabled = false

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#25be6a)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#ee5396)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#08bdba)]($style)'

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#be95ff)]($style)'

[time]
disabled = true
time_format = "%R"                           # Hour:Minute Format
format = '[[   $time ](fg:#08bdba)]($style)'

[os]
disabled = true
style = "fg:os"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = " 󰣭 "
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[conda]
format = '[[ $symbol ($version) ](fg:#08bdba)]($style)'
