-- Colorscheme plugins for every switchable theme.
--
-- Which one is ACTIVE comes from lua/config/theme.lua, a file GENERATED by
-- scripts/theme.sh from themes/<name>.sh. Switch everything with `theme <name>`;
-- do not hardcode a colorscheme here.
--
-- Both plugins load eagerly: they only define highlight groups, and LazyVim
-- needs the active one available before it applies opts.colorscheme.
local theme = require("config.theme")

return {
  { "folke/tokyonight.nvim", lazy = false, priority = 1000 },
  { "Shatur/neovim-ayu", lazy = false, priority = 1000 },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = theme.colorscheme,
    },
  },
}
